### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by ssokolow** [beltoforion/Galaxy-Renderer#3]
Please add a `LICENSE` file to the root of the repository, containing the text of the license under which you're releasing this code.

[Without a license](https://choosealicense.com/no-permission/), stuff is under "All Rights Reserved" terms, meaning people aren't allowed to do anything beyond what the GitHub Terms of Service require you to agree to as part of uploading it.

See https://choosealicense.com/ for more.

**Comment by beltoforion** [comment]
sone

**Comment by ssokolow** [comment]
Thanks... and sorry for taking so long to say that. It's a busy time right now.
