### ISSUE TITLE
Problem rendering in iOS

### ISSUE THREAD

**Issue by Aarkham** [beltoforion/Galaxy-Renderer#7]
Hi

Thanks for sharing the Galaxy Renderer, it´s really nice.
I have adapted it as a background to a game I'm writing and I found that it has problems in iOS. The issue is that sometimes the point size is negative and iOS then renders it wrong.

I have added:

     gl_PointSize=max(gl_PointSize,0.0);

at the end of the vertex shader and now it works Ok. Don't know if there is a better way to correct it. Hope it helps.

I attach a screen shot of my game

![acImage_2021-07-12_18-33-11](https://user-images.githubusercontent.com/8093144/125325936-cdcbd880-e341-11eb-91af-346f85f5f029.png)

**Comment by beltoforion** [comment]
Sorry for not noticing your post here. It went under my radar because i had notifications turned off. I will update the code. Thanks for submitting the fix.
